version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  server:
    image: nestjs-jwt-profile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "${HOST}"
      PORT: 3000
      PAPERTRAIL_HOST: "${PAPERTRAIL_HOST}"
      PAPERTRAIL_PORT: "${PAPERTRAIL_PORT}"
    depends_on:
      - postgres
    links:
      - postgres

volumes: 
  pgdata:

